" to do:

set guifont=Monaco:h16
set runtimepath+=$HOME/.local/share/nvim

" set runtimepath+=$HOME/dotfiles/vim-common
call plug#begin(expand('~/.config/nvim/plugged'))
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-unimpaired'           " for bubbling
Plug 'justinmk/vim-sneak'
Plug 'kshenoy/vim-signature'
Plug 'airblade/vim-gitgutter'
Plug 'qpkorr/vim-bufkill'             " :BD is very useful
Plug 'itchyny/lightline.vim'         
Plug 'ap/vim-buftabline'
Plug 'mhartington/oceanic-next'
Plug 'reedes/vim-pencil'
call plug#end()

source $HOME/dotfiles/vim-common/line.vimrc   " for the lightline config

let g:sneak#label = 1
let g:sneak#streak = 1
nmap s <plug>sneaklabel_s
nmap s <plug>sneaklabel_s

let g:pencil#wrapModeDefault = 'soft'

set autoread
augroup autoSaveAndRead
	autocmd!
	autocmd TextChanged,InsertLeave,FocusLost * silent! wall
	autocmd CursorHold * silent! checktime
augroup END

let g:pencil#wrapModeDefault = 'soft'   " default is 'hard'
augroup emailConfig
	autocmd!
  autocmd FileType markdown,mkd call pencil#init()
  autocmd FileType text         call pencil#init()
augroup END


source $HOME/dotfiles/vim-common/remaps.vim
source $HOME/dotfiles/vim-common/sets.vim
source $HOME/dotfiles/vim-common/gui.vim


" done.
