"
" Author: [Patrick Ball](mailto://pball@hrdag.org)
" git@github.com:vm-wylbur/pb-dotfiles.git
" (c) 2018 [HRDAG](https://hrdag.org), GPL-2 or later
"
" pb-dotfiles/macvim/gvimrc  symlinked to ~/.vimrc

set guifont=Monaco:h16
set runtimepath+=$HOME/.local/share/nvim

" set runtimepath+=$HOME/dotfiles/vim-common
call plug#begin(expand('~/.config/nvim/plugged'))
" Plug 'tpope/vim-commentary'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-unimpaired'           " for bubbling
Plug 'justinmk/vim-sneak'
Plug 'kshenoy/vim-signature'
Plug 'airblade/vim-gitgutter'
Plug 'qpkorr/vim-bufkill'             " :BD is very useful
Plug 'machakann/vim-highlightedyank'  " blink
Plug 'itchyny/lightline.vim'
Plug 'ap/vim-buftabline'
Plug 'mhartington/oceanic-next'
Plug 'reedes/vim-pencil'
Plug 'ntpeters/vim-better-whitespace' " to remove trailing whitespace on save
call plug#end()

filetype plugin indent on

source $HOME/dotfiles/vim-common/line.vimrc   " for the lightline config
source $HOME/dotfiles/vim-common/plugins.vim

if has("gui_macvim")
	let macvim_hig_shift_movement = 1
endif
set lines=60
set columns=85

source $HOME/dotfiles/vim-common/remaps.vim
source $HOME/dotfiles/vim-common/sets.vim
source $HOME/dotfiles/vim-common/gui.vim
source $HOME/dotfiles/vim-common/autogrp.vim

nnoremap <leader>ev :e $HOME/dotfiles/macvim/gvimrc<cr>
" done.
