#!/bin/bash
#
# vs
# - If $1 is a file, just open it; if it is Session.vim, open as session
# - if $1 is a dir and -f Session.vim, open the session
# - if $1 is a dir, open all of it, and start Obsession
# 
# install by symlinking to ~/bin/vs 
# 
usage="$(basename "$0") [-h] file(s) -- opens vim with files or Session
where:
   -h show this help text
"
if [[ "$1" == "-h" ]] || [[ $# -eq 0 ]] ; then
    echo "$usage" >&2
    exit 1
fi

if [[ $# -gt 1 ]] ; then
    # open all the files
    echo "more than 1 arg=$# : $*"
else
    if [[ -f $1 ]] ; then
        if [[ "$(basename $1)" == "Session.vim" ]]; then
            echo "found Session.vim"
        else
            echo "a non-session file found"
        fi
    else
        if [[ -d $1 ]] ; then
            echo "it's a directory"
            # if there's Session.vim open it,
            # otherwise open everything in the dir and start Session
        else
            echo "I can't handle whatever this is"
        fi
    fi
fi
