#
# :Author: Sorin Ionescu <sorin.ionescu@gmail.com>
# :customized: PB
# Last modified: <Tue 19 Dec 2017 04:56:27 PM PST>
#
# Executes commands at the start of an interactive session.

# Make sure the shell is interactive
case $- in
    *i*) ;;
    *) return ;;
esac
#
# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# init fasd on eleanor; fasd is part of pretzo on petunia
case $HOST in
  (petunia) SED="gsed" ;;
  (eleanor)
    eval "$(fasd --init auto)"
    SED="sed"
    ;;
  (*) eval "$(fasd --init auto)"
    SED="sed"
    ;;
esac

# Customize to your needs...
# PB additions here
export TERM=xterm-256color

# ---paths-----
# this starts with the output of /usr/libexec/path_helper
PATH="/usr/local/sbin:$PATH"
PATH="$HOME/anaconda3/bin:$PATH"
PATH+=":$HOME/bin"
PATH+=":/Applications/RStudio.app/Contents/MacOS/pandoc"
PATH+=":$HOME/projects/hrdag/snap/bin"
PATH+=":$HOME/.cargo/bin"
export PATH


# ---shell options-----
setopt APPEND_HISTORY
setopt BANG_HIST
setopt EXTENDED_HISTORY
setopt HIST_IGNORE_DUPS
setopt INC_APPEND_HISTORY
setopt AUTO_PUSHD
setopt PUSHD_IGNORE_DUPS
setopt CHASE_LINKS
setopt ALWAYS_TO_END

# setting up fzf keybindings
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# ---aliases-----
alias gs="git status"
# alias gl="git log --graph --pretty=oneline --abbrev-commit"
# alias gl='git log --pretty=format:"%h%x09%an%x09%ad%x09%s"'
alias gl="$HOME/bin/git-log-compact"
alias gd="git diff"
alias gdc="git diff --cached"

alias mm="make -f src/Makefile"
alias ccat="pygmentize $1"

# List all files colorized in long format
# Detect which `ls` flavor is in use
if ls --color > /dev/null 2>&1; then # GNU `ls`
	colorflag="--color"
else # OS X `ls`
	colorflag="-G"
fi
alias ll="ls -ltrF ${colorflag}"
# List all files colorized in long format, including dot files
alias la="ls -laF ${colorflag}"
# List only directories
alias lsd="ls -lF ${colorflag} | grep --color=never '^d'"

# overriding alias=j in zprezto's fasd module: use fzf, don't print scores
alias j='xdir=$(fasd -ld | fzf --tac) && cd "$xdir"'

# use fzf for history search
alias h='print -z $(fc -l 1 | fzf +s --tac | $SED -re "s/^\s*[0-9]+\s*//")'

# ---env vars-----
export EDITOR='vim'
export LANG='en_US.UTF-8';
export LC_ALL='en_US.UTF-8';

# ---for zsh-----
export KEYTIMEOUT=1
bindkey -e
bindkey '^?' backward-delete-char
bindkey '^P' up-history
bindkey '^N' down-history
bindkey '^?' backward-delete-char
bindkey '^h' backward-delete-char
bindkey '^w' backward-kill-word
bindkey '^r' history-incremental-search-backward

autoload -U zmv


# ---local-----
export HOMEBREW_GITHUB_API_TOKEN="7105df98ca887eda6aa4125926a86945b5da40bd"

export LOCALGIT="/Users/pball/projects"
export HRDAGGIT="$LOCALGIT/hrdag"
export PERSONALGIT="$LOCALGIT/personal"

prompt pball
# done.

