#
# :Author: Sorin Ionescu <sorin.ionescu@gmail.com>
# :customized: PB
# Last modified: <Sat 02 Dec 2017 01:18:37 PM PST>
#
# Executes commands at the start of an interactive session.

# Make sure the shell is interactive
case $- in
    *i*) ;;
    *) return ;;
esac
#
# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
# PB additions here
bindkey -v '^?' backward-delete-char
export TERM=xterm-256color

# ---paths-----
# this starts with the output of /usr/libexec/path_helper
PATH="/usr/local/sbin:$PATH"
PATH+=":$HOME/bin"
PATH+=":$HOME/anaconda3/bin"
PATH+=":/Applications/RStudio.app/Contents/MacOS/pandoc"
PATH+=":$HOME/projects/hrdag/snap/bin"
PATH+=":$HOME/.cargo/bin"
export PATH


# ---aliases-----
alias gs="git status"
# alias gl="git log --graph --pretty=oneline --abbrev-commit"
# alias gl='git log --pretty=format:"%h%x09%an%x09%ad%x09%s"'
alias gl="$HOME/bin/git-log-compact"

alias mm="make -f src/Makefile"
alias ccat="pygmentize $1"

# List all files colorized in long format
# Detect which `ls` flavor is in use
if ls --color > /dev/null 2>&1; then # GNU `ls`
	colorflag="--color"
else # OS X `ls`
	colorflag="-G"
fi
alias ll="ls -ltrF ${colorflag}"
# List all files colorized in long format, including dot files
alias la="ls -laF ${colorflag}"
# List only directories
alias lsd="ls -lF ${colorflag} | grep --color=never '^d'"

# ---env vars-----
export EDITOR='vim'
export LANG='en_US.UTF-8';
export LC_ALL='en_US.UTF-8';

export HOMEBREW_GITHUB_API_TOKEN="7105df98ca887eda6aa4125926a86945b5da40bd"

export LOCALGIT="/Users/pball/projects"
export HRDAGGIT="$LOCALGIT/hrdag"
export PERSONALGIT="$LOCALGIT/personal"

# done.
