import = [
    "~/.config/alacritty/themes/themes/nightfox.toml"
]

[window]
decorations = "full"

[font]
size = 16
# [font.normal]
# family = "IBM Plex Mono"
# style = "Regular"
# [font.bold]
# family = "IBM Plex Mono"
# style = "Bold"
[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[terminal]
osc52 = "CopyPaste"

[cursor]
[cursor.style]
blinking = "Always"

# done

